from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time  # Import the time module for adding delays

chrome_options = Options()
chrome_options.add_argument("--headless")  # Run in headless mode
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--disable-extensions")

# Initialize the WebDriver without specifying a path (GitHub Actions default)
driver = webdriver.Chrome(options=chrome_options)

# List of URLs to process
urls = [
    urls = [
"https://gdmirrorbot.nl/file/iti0k07",
"https://gdmirrorbot.nl/file/ocz5x20",
"https://gdmirrorbot.nl/file/h3g62au",
"https://gdmirrorbot.nl/file/zrz93c7",
"https://gdmirrorbot.nl/file/zte8yz4",
"https://gdmirrorbot.nl/file/b46mueq",
"https://gdmirrorbot.nl/file/oj2out6",
"https://gdmirrorbot.nl/file/eap0r23",
"https://gdmirrorbot.nl/file/ep1mhkk",
"https://gdmirrorbot.nl/file/vopgk9z",
"https://gdmirrorbot.nl/file/j05h0fo",
"https://gdmirrorbot.nl/file/f5ieock",
"https://gdmirrorbot.nl/file/n4plm3h",
"https://gdmirrorbot.nl/file/nc4acx0",
"https://gdmirrorbot.nl/file/qwvaqkq",
"https://gdmirrorbot.nl/file/hhc810j",
"https://gdmirrorbot.nl/file/gv22pnt",
"https://gdmirrorbot.nl/file/w4bq6ss",
"https://gdmirrorbot.nl/file/qgx1k3z",
"https://gdmirrorbot.nl/file/jlnsy28",
"https://gdmirrorbot.nl/file/oiy4pk1",
"https://gdmirrorbot.nl/file/ab8x2ye",
"https://gdmirrorbot.nl/file/wftw7ys",
"https://gdmirrorbot.nl/file/l35t99e",
"https://gdmirrorbot.nl/file/pipl4p6",
"https://gdmirrorbot.nl/file/aj5bdsc",
"https://gdmirrorbot.nl/file/uwk23f6",
"https://gdmirrorbot.nl/file/ihbiw9d",
"https://gdmirrorbot.nl/file/wqsabbt",
"https://gdmirrorbot.nl/file/iknnzpx",
"https://gdmirrorbot.nl/file/nmnd15z",
"https://gdmirrorbot.nl/file/ekbwv51",
"https://gdmirrorbot.nl/file/ehul41h",
"https://gdmirrorbot.nl/file/o3hi4vk",
"https://gdmirrorbot.nl/file/gcm26mx",
"https://gdmirrorbot.nl/file/rbl9k1s",
"https://gdmirrorbot.nl/file/f6b599y",
"https://gdmirrorbot.nl/file/mn6uxpa",
"https://gdmirrorbot.nl/file/wzm8yln",
"https://gdmirrorbot.nl/file/bo1du6o",
"https://gdmirrorbot.nl/file/sqxq3kw",
"https://gdmirrorbot.nl/file/t8cdbqg",
"https://gdmirrorbot.nl/file/kxw65hz",
"https://gdmirrorbot.nl/file/uzek1j2",
"https://gdmirrorbot.nl/file/pza6hz6",
"https://gdmirrorbot.nl/file/lsu81d3",
"https://gdmirrorbot.nl/file/k602toy",
"https://gdmirrorbot.nl/file/xz6h15f",
"https://gdmirrorbot.nl/file/ef5ygz2",
"https://gdmirrorbot.nl/file/f6b1vs7",
"https://gdmirrorbot.nl/file/xont68k",
"https://gdmirrorbot.nl/file/f66rj6b",
"https://gdmirrorbot.nl/file/tqkex4a",
"https://gdmirrorbot.nl/file/a5ijkqv",
"https://gdmirrorbot.nl/file/fx06fp1",
"https://gdmirrorbot.nl/file/km068b7",
"https://gdmirrorbot.nl/file/kdtfbpr",
"https://gdmirrorbot.nl/file/q6gnpxj",
"https://gdmirrorbot.nl/file/u5qn0k0",
"https://gdmirrorbot.nl/file/dhz3g0a",
"https://gdmirrorbot.nl/file/jhk1hnh",
"https://gdmirrorbot.nl/file/ytckkhm",
"https://gdmirrorbot.nl/file/tubj7io",
"https://gdmirrorbot.nl/file/wbrvyyi",
"https://gdmirrorbot.nl/file/kgil0sv",
"https://gdmirrorbot.nl/file/vqlkolq",
"https://gdmirrorbot.nl/file/u8bloyj",
"https://gdmirrorbot.nl/file/c1fo2kv",
"https://gdmirrorbot.nl/file/lthhj4u",
"https://gdmirrorbot.nl/file/msbart7",
"https://gdmirrorbot.nl/file/syjl4f4",
"https://gdmirrorbot.nl/file/mk83qg0",
"https://gdmirrorbot.nl/file/inhptx6",
"https://gdmirrorbot.nl/file/xsj8acc",
"https://gdmirrorbot.nl/file/w43q4vf",
"https://gdmirrorbot.nl/file/xwmlab3",
"https://gdmirrorbot.nl/file/p0qmuuy",
"https://gdmirrorbot.nl/file/qpkyox3",
"https://gdmirrorbot.nl/file/fdpjwkc",
"https://gdmirrorbot.nl/file/eug3o8s",
"https://gdmirrorbot.nl/file/tmqy3n0",
"https://gdmirrorbot.nl/file/sqkg3xh",
"https://gdmirrorbot.nl/file/wl3vdun",
"https://gdmirrorbot.nl/file/sxfsp0w",
"https://gdmirrorbot.nl/file/awaf5vy",
"https://gdmirrorbot.nl/file/lr58p11",
"https://gdmirrorbot.nl/file/i6lv8g3",
"https://gdmirrorbot.nl/file/vrbycsy",
"https://gdmirrorbot.nl/file/kdd5bnv",
"https://gdmirrorbot.nl/file/quvw397",
"https://gdmirrorbot.nl/file/qhey6i6",
"https://gdmirrorbot.nl/file/muwbeeh",
"https://gdmirrorbot.nl/file/eomr9yh",
"https://gdmirrorbot.nl/file/i0dofhp",
"https://gdmirrorbot.nl/file/jv9h92g",
"https://gdmirrorbot.nl/file/u7j0vfr",
"https://gdmirrorbot.nl/file/r18hsxb",
"https://gdmirrorbot.nl/file/bxp7yk0",
"https://gdmirrorbot.nl/file/ru2wl27",
"https://gdmirrorbot.nl/file/wucuvdn",
"https://gdmirrorbot.nl/file/ja74zse",
"https://gdmirrorbot.nl/file/oamgpkc",
"https://gdmirrorbot.nl/file/p89c1it",
"https://gdmirrorbot.nl/file/oc01qon",
"https://gdmirrorbot.nl/file/g3x3tth",
"https://gdmirrorbot.nl/file/qt7egq3",
"https://gdmirrorbot.nl/file/aj60k9j",
"https://gdmirrorbot.nl/file/vqd7vms",
"https://gdmirrorbot.nl/file/tsflzkv",
"https://gdmirrorbot.nl/file/dth6qqh",
"https://gdmirrorbot.nl/file/n6rnyzh",
"https://gdmirrorbot.nl/file/awsjt7u",
"https://gdmirrorbot.nl/file/g0ydy03",
"https://gdmirrorbot.nl/file/use250w",
"https://gdmirrorbot.nl/file/o58hi12",
"https://gdmirrorbot.nl/file/g07icff",
"https://gdmirrorbot.nl/file/rkjcpkg",
"https://gdmirrorbot.nl/file/n599la0",
"https://gdmirrorbot.nl/file/za3u279",
"https://gdmirrorbot.nl/file/fdeevff",
"https://gdmirrorbot.nl/file/z5zvpp8",
"https://gdmirrorbot.nl/file/fcpmvit",
"https://gdmirrorbot.nl/file/aklwwp6",
"https://gdmirrorbot.nl/file/jzgrt6d",
"https://gdmirrorbot.nl/file/g7joi93",
"https://gdmirrorbot.nl/file/ulwat3t",
"https://gdmirrorbot.nl/file/aijtv5m",
"https://gdmirrorbot.nl/file/t7ktdhu",
"https://gdmirrorbot.nl/file/bel5z9k",
"https://gdmirrorbot.nl/file/u4h8as8",
"https://gdmirrorbot.nl/file/vc555o3",
"https://gdmirrorbot.nl/file/fwh54z2",
"https://gdmirrorbot.nl/file/m6qgvul",
"https://gdmirrorbot.nl/file/ka04quu",
"https://gdmirrorbot.nl/file/q1w2rdl",
"https://gdmirrorbot.nl/file/dcpcq22",
"https://gdmirrorbot.nl/file/eljgn8o",
"https://gdmirrorbot.nl/file/tlmswd7",
"https://gdmirrorbot.nl/file/j8bphpt",
"https://gdmirrorbot.nl/file/odtm2jc",
"https://gdmirrorbot.nl/file/yg7ordy",
"https://gdmirrorbot.nl/file/yl8wjku",
"https://gdmirrorbot.nl/file/x1flek6",
"https://gdmirrorbot.nl/file/ewiaddm",
"https://gdmirrorbot.nl/file/wxfoubn",
"https://gdmirrorbot.nl/file/usqaiu4",
"https://gdmirrorbot.nl/file/bnaa8ny",
"https://gdmirrorbot.nl/file/zdd6c0g",
"https://gdmirrorbot.nl/file/mly2r6p",
"https://gdmirrorbot.nl/file/v8gy0gy",
"https://gdmirrorbot.nl/file/gltvo3k",
"https://gdmirrorbot.nl/file/kwdtzue",
"https://gdmirrorbot.nl/file/gtahl15",
"https://gdmirrorbot.nl/file/bv9ztis",
"https://gdmirrorbot.nl/file/kxgimr2",
"https://gdmirrorbot.nl/file/kr3s9lp",
"https://gdmirrorbot.nl/file/oqy7ajx",
"https://gdmirrorbot.nl/file/cskl1sx",
"https://gdmirrorbot.nl/file/sa03fqr",
"https://gdmirrorbot.nl/file/n6amt4t",
"https://gdmirrorbot.nl/file/y9b14s6",
"https://gdmirrorbot.nl/file/odd1gl9",
"https://gdmirrorbot.nl/file/q0d2cat",
"https://gdmirrorbot.nl/file/yhequcx",
"https://gdmirrorbot.nl/file/amdrr85",
"https://gdmirrorbot.nl/file/nwdlyf7",
"https://gdmirrorbot.nl/file/t44d9rl",
"https://gdmirrorbot.nl/file/v3d0ni4",
"https://gdmirrorbot.nl/file/cx6crid",
"https://gdmirrorbot.nl/file/rz2cnqs",
"https://gdmirrorbot.nl/file/byrbl3u",
"https://gdmirrorbot.nl/file/d2w41ea",
"https://gdmirrorbot.nl/file/p5x1okl",
"https://gdmirrorbot.nl/file/tfncb5i",
"https://gdmirrorbot.nl/file/v7jkj4a",
"https://gdmirrorbot.nl/file/dpy54pi",
"https://gdmirrorbot.nl/file/mmzla1r",
"https://gdmirrorbot.nl/file/liz3ds6",
"https://gdmirrorbot.nl/file/c2y62n8",
"https://gdmirrorbot.nl/file/kwaftmh",
"https://gdmirrorbot.nl/file/l0kvtvq",
"https://gdmirrorbot.nl/file/eh6tcll",
"https://gdmirrorbot.nl/file/l4updv5",
"https://gdmirrorbot.nl/file/axvbhtp",
"https://gdmirrorbot.nl/file/xndguf8",
"https://gdmirrorbot.nl/file/zre8xxy",
"https://gdmirrorbot.nl/file/iiwyrmv",
"https://gdmirrorbot.nl/file/k8oq1bj",
"https://gdmirrorbot.nl/file/stdunya",
"https://gdmirrorbot.nl/file/ca47yhc",
"https://gdmirrorbot.nl/file/fa95ncm",
"https://gdmirrorbot.nl/file/vjjevp3",
"https://gdmirrorbot.nl/file/u4sfsd3",
"https://gdmirrorbot.nl/file/wwbg7rn",
"https://gdmirrorbot.nl/file/p0n7d7d",
"https://gdmirrorbot.nl/file/lzn3ixb",
"https://gdmirrorbot.nl/file/beoeio4",
"https://gdmirrorbot.nl/file/ruunipo",
"https://gdmirrorbot.nl/file/ukz4a5q",
"https://gdmirrorbot.nl/file/yvda8ir",
"https://gdmirrorbot.nl/file/yf8s73l",
"https://gdmirrorbot.nl/file/e5ccs4h",
"https://gdmirrorbot.nl/file/c6e4cve",
"https://gdmirrorbot.nl/file/rcyhuz0",
"https://gdmirrorbot.nl/file/cnv4zun",
"https://gdmirrorbot.nl/file/xiyv2wc",
"https://gdmirrorbot.nl/file/m8p3ar4",
"https://gdmirrorbot.nl/file/o59wtiu",
"https://gdmirrorbot.nl/file/jlayhhs",
"https://gdmirrorbot.nl/file/oub62zp",
"https://gdmirrorbot.nl/file/h75z7ok",
"https://gdmirrorbot.nl/file/kzgp3ds",
"https://gdmirrorbot.nl/file/le75inc",
"https://gdmirrorbot.nl/file/knc0jdv",
"https://gdmirrorbot.nl/file/pie57pe",
"https://gdmirrorbot.nl/file/irh4not",
"https://gdmirrorbot.nl/file/flkqgqm",
"https://gdmirrorbot.nl/file/pejb9hs",
"https://gdmirrorbot.nl/file/tgi6icl",
"https://gdmirrorbot.nl/file/u8hujgr",
"https://gdmirrorbot.nl/file/zj4pn9y",
"https://gdmirrorbot.nl/file/npzrtk8",
"https://gdmirrorbot.nl/file/lgwwhor",
"https://gdmirrorbot.nl/file/j584qqt",
"https://gdmirrorbot.nl/file/u975r2h",
"https://gdmirrorbot.nl/file/desux3j",
"https://gdmirrorbot.nl/file/bpksr1j",
"https://gdmirrorbot.nl/file/i3x91cz",
"https://gdmirrorbot.nl/file/bdm4jy1",
"https://gdmirrorbot.nl/file/i9m4blo",
"https://gdmirrorbot.nl/file/zpobgkc",
"https://gdmirrorbot.nl/file/z5fp1mo",
"https://gdmirrorbot.nl/file/ft44s4s",
"https://gdmirrorbot.nl/file/aoqrpd2",
"https://gdmirrorbot.nl/file/ikxu7mi",
"https://gdmirrorbot.nl/file/a8de99b",
"https://gdmirrorbot.nl/file/qh5b25e",
"https://gdmirrorbot.nl/file/wph19p7",
"https://gdmirrorbot.nl/file/n3ieh7u",
"https://gdmirrorbot.nl/file/hv4x66v",
"https://gdmirrorbot.nl/file/l4qxn5k",
"https://gdmirrorbot.nl/file/efa9t6q",
"https://gdmirrorbot.nl/file/blitdg3",
"https://gdmirrorbot.nl/file/j79qwza",
"https://gdmirrorbot.nl/file/tphqcoj",
"https://gdmirrorbot.nl/file/y1pszcw",
"https://gdmirrorbot.nl/file/ugtkpme",
"https://gdmirrorbot.nl/file/r5wykoj",
"https://gdmirrorbot.nl/file/hr4reow",
"https://gdmirrorbot.nl/file/pqbswj2",
"https://gdmirrorbot.nl/file/wiort8x",
"https://gdmirrorbot.nl/file/wz0da2t",
"https://gdmirrorbot.nl/file/za0yexz",
"https://gdmirrorbot.nl/file/k9vsxv9",
"https://gdmirrorbot.nl/file/vxi26z5",
"https://gdmirrorbot.nl/file/lrxpqd5",
"https://gdmirrorbot.nl/file/izsrou0",
"https://gdmirrorbot.nl/file/yfujd2e",
"https://gdmirrorbot.nl/file/jv29ogp",
"https://gdmirrorbot.nl/file/j44h3y8",
"https://gdmirrorbot.nl/file/uj4ncu2",
"https://gdmirrorbot.nl/file/m0qyu8b",
"https://gdmirrorbot.nl/file/gad1isx",
"https://gdmirrorbot.nl/file/rmzzh61",
"https://gdmirrorbot.nl/file/ap8aog4",
"https://gdmirrorbot.nl/file/rak3usn",
"https://gdmirrorbot.nl/file/kgdqjsd",
"https://gdmirrorbot.nl/file/fi1wkwf",
"https://gdmirrorbot.nl/file/eaxefs6",
"https://gdmirrorbot.nl/file/ykosigf",
"https://gdmirrorbot.nl/file/v63fgha",
"https://gdmirrorbot.nl/file/zemh8dw",
"https://gdmirrorbot.nl/file/joafmhl",
"https://gdmirrorbot.nl/file/bxdor5j",
"https://gdmirrorbot.nl/file/rer2x8y",
"https://gdmirrorbot.nl/file/nf9vj8p",
"https://gdmirrorbot.nl/file/pi6rso0",
"https://gdmirrorbot.nl/file/kzxd0fx",
"https://gdmirrorbot.nl/file/uahgywl",
"https://gdmirrorbot.nl/file/zve74ft",
"https://gdmirrorbot.nl/file/tj5snge",
"https://gdmirrorbot.nl/file/cag4ypd",
"https://gdmirrorbot.nl/file/yw442bk",
"https://gdmirrorbot.nl/file/zy155jm",
"https://gdmirrorbot.nl/file/kw1cp9w",
"https://gdmirrorbot.nl/file/njxdmo5",
"https://gdmirrorbot.nl/file/r2trzs0",
"https://gdmirrorbot.nl/file/vawv4o2",
"https://gdmirrorbot.nl/file/gbkuhbn",
"https://gdmirrorbot.nl/file/d75d5x8",
"https://gdmirrorbot.nl/file/zv46j8x",
"https://gdmirrorbot.nl/file/fdq0b6m",
"https://gdmirrorbot.nl/file/op6ry75",
"https://gdmirrorbot.nl/file/in3ukke",
"https://gdmirrorbot.nl/file/ax7bq0f",
"https://gdmirrorbot.nl/file/jzmkq04",
"https://gdmirrorbot.nl/file/lqkbnzh",
"https://gdmirrorbot.nl/file/y5c3jhu",
"https://gdmirrorbot.nl/file/juhdbk8",
"https://gdmirrorbot.nl/file/bmu3elo",
"https://gdmirrorbot.nl/file/b46si7l",
"https://gdmirrorbot.nl/file/ov61qn5",
"https://gdmirrorbot.nl/file/lupa2vk",
"https://gdmirrorbot.nl/file/jpnm2ix",
"https://gdmirrorbot.nl/file/gwk6c66",
"https://gdmirrorbot.nl/file/deyka0i",
"https://gdmirrorbot.nl/file/phrodsq",
"https://gdmirrorbot.nl/file/t9ni4wp",
"https://gdmirrorbot.nl/file/d6jpta3",
"https://gdmirrorbot.nl/file/sfkrnxk",
"https://gdmirrorbot.nl/file/hzwi2th",
"https://gdmirrorbot.nl/file/cs33bxy",
"https://gdmirrorbot.nl/file/ay3xheq",
"https://gdmirrorbot.nl/file/erqvc42",
"https://gdmirrorbot.nl/file/v5ulzgj",
"https://gdmirrorbot.nl/file/kb6tfah",
"https://gdmirrorbot.nl/file/nt7dv69",
"https://gdmirrorbot.nl/file/hpv9aq8",
"https://gdmirrorbot.nl/file/aghs38e",
"https://gdmirrorbot.nl/file/ozxl36p",
"https://gdmirrorbot.nl/file/v2edeha",
"https://gdmirrorbot.nl/file/xe0bnwv",
"https://gdmirrorbot.nl/file/ish7gqg",
"https://gdmirrorbot.nl/file/qam5n22",
"https://gdmirrorbot.nl/file/p9cdl4u",
"https://gdmirrorbot.nl/file/h13a0t7",
"https://gdmirrorbot.nl/file/m1oto58",
"https://gdmirrorbot.nl/file/dzh2gsh",
"https://gdmirrorbot.nl/file/kzf5c9s",
"https://gdmirrorbot.nl/file/qyvxt1x",
"https://gdmirrorbot.nl/file/f6jwijv",
"https://gdmirrorbot.nl/file/s4tx7h2",
"https://gdmirrorbot.nl/file/rhkedot",
"https://gdmirrorbot.nl/file/rvmnu3w",
"https://gdmirrorbot.nl/file/oc5pdma",
"https://gdmirrorbot.nl/file/iyjnt7m",
"https://gdmirrorbot.nl/file/ljmxl9h",
"https://gdmirrorbot.nl/file/b0az06z",
"https://gdmirrorbot.nl/file/z5lou1t",
"https://gdmirrorbot.nl/file/o2n9g3w",
"https://gdmirrorbot.nl/file/lvc9vq5",
"https://gdmirrorbot.nl/file/d5r9v8q",
"https://gdmirrorbot.nl/file/irr337d",
"https://gdmirrorbot.nl/file/s6pedii",
"https://gdmirrorbot.nl/file/m2bn07b",
"https://gdmirrorbot.nl/file/w14q6sy",
"https://gdmirrorbot.nl/file/bjpxsia",
"https://gdmirrorbot.nl/file/mmons5y",
"https://gdmirrorbot.nl/file/kfsdqd6",
"https://gdmirrorbot.nl/file/wrdmzjf",
"https://gdmirrorbot.nl/file/gli4dah",
"https://gdmirrorbot.nl/file/yuzuq5m",
"https://gdmirrorbot.nl/file/vnc70aw",
"https://gdmirrorbot.nl/file/twvpqsc",
"https://gdmirrorbot.nl/file/nhg94wv",
"https://gdmirrorbot.nl/file/os3weqe",
"https://gdmirrorbot.nl/file/ch70suh",
"https://gdmirrorbot.nl/file/vhaeqb9",
"https://gdmirrorbot.nl/file/lku8c2d"
]

# Function to process each link
def process_link(url):
    print(f"Accessing URL: {url}")
    driver.get(url)
    
    try:
        print("Waiting for redirection...")
        WebDriverWait(driver, 10).until(EC.url_contains("snapinsta.storyy.shop"))
        redirected_url = driver.current_url
        print(f"Redirected to: {redirected_url}")

        if "snapinsta.storyy.shop" in redirected_url:
            try:
                print("Waiting for 'Generate New Link' button to become visible...")
                generate_button = WebDriverWait(driver, 10).until(
                    EC.visibility_of_element_located((By.XPATH, "//input[@type='submit' and @value='Generate New Link']"))
                )
                print("Scrolling to the 'Generate New Link' button...")
                driver.execute_script("arguments[0].scrollIntoView(true);", generate_button)

                # Use JavaScript click to avoid interception issues
                print("Clicking the 'Generate New Link' button...")
                driver.execute_script("arguments[0].click();", generate_button)
                print("Successfully clicked the 'Generate New Link' button.")

                # Optionally, wait for the new page to load after clicking
                print("Waiting for the new page to load...")
                WebDriverWait(driver, 10).until(EC.staleness_of(generate_button))
                print("New page has loaded.")

            except Exception as e:
                print(f"An error occurred while trying to click the button: {e}")
        else:
            print("Redirection did not lead to the expected site.")

    except Exception as e:
        print(f"An error occurred during redirection: {e}")

# Loop through each URL and process with a 1-minute delay
for url in urls:
    process_link(url)
    print("Waiting for 1 minute before proceeding to the next URL...")
    time.sleep(60)  # Wait for 1 minute

# Close the WebDriver
print("Closing the WebDriver...")
driver.quit()
print("Done.")
